if(NOT PROJECT_IS_TOP_LEVEL OR __template__project_name_PACKAGING_MAINTAINER_MODE)
    option(__template__project_name_ENABLE_IPO "Enable IPO/LTO" OFF)
  else()
    option(__template__project_name_ENABLE_IPO "Enable IPO/LTO" ON)
  endif()

macro(__template__project_name_enable_ipo)
  include(CheckIPOSupported)
  check_ipo_supported(RESULT result OUTPUT output)
  if(result)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
  else()
    message(SEND_ERROR "IPO is not supported: ${output}")
  endif()
endmacro()
__template__project_name_enable_ipo()