if(NOT PROJECT_IS_TOP_LEVEL OR myproject_PACKAGING_MAINTAINER_MODE)
  option(myproject_ENABLE_SANITIZER_ADDRESS "Enable undefined sanitizer" OFF)
else()
  option(myproject_ENABLE_SANITIZER_ADDRESS "Enable undefined sanitizer" ${SUPPORTS_UBSAN})
endif()