if(NOT PROJECT_IS_TOP_LEVEL OR myproject_PACKAGING_MAINTAINER_MODE)
  option(myproject_ENABLE_SANITIZER_THREAD "Enable thread sanitizer" OFF)
else()
  option(myproject_ENABLE_SANITIZER_THREAD "Enable thread sanitizer" ${SUPPORTS_ASAN})
endif()