if(NOT PROJECT_IS_TOP_LEVEL OR myproject_PACKAGING_MAINTAINER_MODE)
  option(myproject_ENABLE_UNITY_BUILD "Enable unity build" OFF)
else()
  option(myproject_ENABLE_UNITY_BUILD "Enable unity build" OFF)
endif()