macro(myproject_enable_ipo)
  include(CheckIPOSupported)
  if(NOT PROJECT_IS_TOP_LEVEL OR myproject_PACKAGING_MAINTAINER_MODE)
    option(myproject_ENABLE_IPO "Enable IPO/LTO" OFF)
  else()
    option(myproject_ENABLE_IPO "Enable IPO/LTO" OFF)
  endif()

  check_ipo_supported(RESULT result OUTPUT output)
  if(result)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
  else()
    message(SEND_ERROR "IPO is not supported: ${output}")
  endif()
  option(myproject_ENABLE_IPO "Enable IPO/LTO" OFF)
endmacro()
myproject_enable_ipo()