if(myproject_ENABLE_HARDENING AND NOT myproject_ENABLE_GLOBAL_HARDENING)
  if(NOT SUPPORTS_UBSAN 
    OR myproject_ENABLE_SANITIZER_UNDEFINED
    OR myproject_ENABLE_SANITIZER_ADDRESS
    OR myproject_ENABLE_SANITIZER_THREAD
    OR myproject_ENABLE_SANITIZER_LEAK)
    set(ENABLE_UBSAN_MINIMAL_RUNTIME FALSE)
  else()
    set(ENABLE_UBSAN_MINIMAL_RUNTIME TRUE)
  endif()
endif()